services:
  # 1. The Python Brain (Backend)
  - type: web
    name: ultra-dj-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true

  # 2. The React UI (Frontend)
  - type: static
    name: ultra-dj-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://ultra-dj-backend.onrender.com 
    autoDeploy: true
